<?php

namespace App\Console\Commands;

use App\Models\Notification;
use Carbon\Carbon;
use Illuminate\Console\Command;

class DeleteOldNotifications extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'notifications:delete-old';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete automatic notifications older than 90 days';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $date = Carbon::now()->subDays(90);

        // Delete automatic notifications older than 90 days
        // We identify automatic notifications by checking if they have a subject (generated by system)
        $deletedCount = Notification::where('created_at', '<', $date)
            ->whereNotNull('subject_type')
            ->whereNotNull('subject_id')
            ->delete();

        $this->info("Deleted {$deletedCount} automatic notifications older than 90 days.");

        return 0;
    }
}
