services:
  app:
    build:
      args:
        user: rashi
        uid: 1001
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rashi
    restart: unless-stopped
    working_dir: /var/www/rashi
    ports:
      - 127.0.0.1:1601:9000
    volumes:
      - ./:/var/www/rashi
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - rashi
      - central_net

  queue:
    build:
      args:
        user: rashi
        uid: 1001
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rashi-queue
    restart: unless-stopped
    working_dir: /var/www/rashi
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./:/var/www/rashi
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - rashi
      - central_net
    depends_on:
      - app

  reverb:
    build:
      args:
        user: rashi
        uid: 1001
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rashi-reverb
    restart: unless-stopped
    working_dir: /var/www/rashi
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - 127.0.0.1:6002:8080
    volumes:
      - ./:/var/www/rashi
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - rashi
      - central_net
    depends_on:
      - app

networks:
  rashi:
    driver: bridge
  central_net:
    external: true
