<?php

namespace App\Jobs;

use App\Models\Notification;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class DeleteOldNotificationsJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        $date = Carbon::now()->subDays(90);

        // Delete automatic notifications older than 90 days
        // We identify automatic notifications by checking if they have a subject (generated by system)
        $deletedCount = Notification::where('created_at', '<', $date)
            ->whereNotNull('subject_type')
            ->whereNotNull('subject_id')
            ->delete();

        Log::info("Deleted {$deletedCount} automatic notifications older than 90 days.");
    }
}
